**3. Del dataset elegido realice la imputaci√≥n por columnas sin scikit-learn.**

In [1]:
import pandas as pd
data = pd.read_csv("../pregunta 1/supermarket_sales - Sheet1.csv")
data.head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,A,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,17:15,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,B,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,13:27,Credit card,164.52,4.761905,8.2260,5.9

In [31]:
#data[data['Total']==None].head()
data.sort_values(by=['cogs'],ascending=True)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
822,784-21-9238,C,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,14:15,Cash,10.17,4.761905,0.5085,5.9
629,308-39-1707,A,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,1/26/2019,18:19,Credit card,12.09,4.761905,0.6045,8.2
223,279-62-1445,C,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2/21/2019,12:38,Cash,12.54,4.761905,0.6270,8.2
443,192-98-7397,C,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,1/8/2019,14:11,Ewallet,12.78,4.761905,0.6390,9.5
402,236-86-3015,C,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2/4/2019,13:38,Ewallet,13.98,4.761905,0.6990,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4
699,751-41-9720,C,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,16:18,Ewallet,975.00,4.761905,48.7500,8.0
557,283-26-5248,C,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,20:23,Ewallet,985.20,4.761905,49.2600,4.5
167,687-47-8271,A,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,16:20,Credit card,989.80,4.761905,49.4900,8.7
350,860-79-0874,C,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2/15/2019,14:53,Credit card,993.00,4.761905,49.6500,6.6

### SimpleImputer
#### Uso: Rellenar valores faltantes en el dataset.
#### Razon de Uso: Los valores faltantes pueden llevar a errores en el analisis y en la construccion de modelos. Imputar estos valores garantiza que todos los datos sean utilizables.

In [32]:
from sklearn.impute import SimpleImputer
#Imputer valores nulos con la media para caracteristicas numericas
imputer=SimpleImputer(strategy='mean')
data[['Total','gross income']]=imputer.fit_transform(data[['Total','gross income']])

In [7]:
data.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

### OneHotEncoder(Codificacion de Variables Categoricas)
#### Uso: Convertir variables categ√≥ricas en variables dummy/indicadoras.
#### Raz√≥n de Uso: Los algoritmos de aprendizaje autom√°tico requieren entradas num√©ricas. La codificaci√≥n one-hot transforma categor√≠as en un formato que los modelos pueden entender.

In [2]:
from sklearn.preprocessing import OneHotEncoder

categorical_features = ['Gender']

categorical_features=[col for col in categorical_features if col in data.columns]

# Aplicar OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
encoded_categories = encoder.fit_transform(data[categorical_features])


columnas_codificadas=encoder.get_feature_names_out(['Gender'])

datos_codificados=pd.DataFrame(encoded_categories,columns=columnas_codificadas)
#print(datos_codificados)
# Concatenar el DataFrame codificado con el original
data2 = pd.concat([data.drop(columns=categorical_features), datos_codificados], axis=1)
data2

,Invoice ID,Branch,City,Customer type,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Gender_Female,Gender_Male
0,750-67-8428,A,Yangon,Member,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,1.0,0.0
1,226-31-3081,C,Naypyitaw,Normal,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,1.0,0.0
2,631-41-3108,A,Yangon,Normal,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,0.0,1.0
3,123-19-1176,A,Yangon,Member,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,0.0,1.0
4,373-73-7910,A,Yangon,Normal,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2,0.0,1.0
996,303-96-2227,B,Mandalay,Normal,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4,1.0,0.0
997,727-02-1313,A,Yangon,Member,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,7.7,0.0,1.0
998,347-56-2442,A,Yangon,Normal,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,4.1,0.0,1.0
999,849-09-3807,A,Yangon,Member,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,6.6,1.0,0.0

### Escalado de caracteristicas numericas
#### Uso: Escalar las caracteristicas numericas para que tengan una media   0 y una desviacion estandar de 1.
#### Razon de Uso: Muchos algoritmos de aprendizaje autom√°tico, especialmente aquellos que se basan en la distancia (como K-means y SVM), funcionan mejor cuando las caracter√≠sticas num√©ricas est√°n en la misma escala.

In [6]:
from sklearn.preprocessing import StandardScaler

numerical_features=['Total','Rating']
scaler=StandardScaler()

data[numerical_features]=scaler.fit_transform(data[numerical_features])
data

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,0.919607,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,1.238443
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,-0.987730,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,1.529527
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,0.071446,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,0.248760
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,0.675780,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,0.830927
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,1.267125,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,-0.973790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,-1.141750,1/29/2019,13:46,Ewallet,40.35,4.761905,2.0175,-0.449840
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,2.846340,3/2/2019,17:16,Ewallet,973.80,4.761905,48.6900,-1.497741
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,-1.178109,2/9/2019,13:22,Cash,31.84,4.761905,1.5920,0.423410
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,-1.032932,2/22/2019,15:33,Cash,65.82,4.761905,3.2910,-1.672391
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,1.327837,2/18/2019,13:28,Cash,618.38,4.761905,30.9190,-0.216974

### Balanceo de clases (submuestreo)
#### Uso: Reducir el desequilibrio de clases en el dataset.
#### Raz√≥n de Uso: El desequilibrio de clases puede causar que los modelos favorezcan la clase mayoritaria. Submuestrear la clase mayoritaria ayuda a equilibrar las clases.

In [13]:
from sklearn.utils import resample
data_majority=data[data['Gender']=='Female']
data_minority=data[data['Gender']=='Male']

data_majority_downsampled=resample(data_majority,replace=False,n_samples=len(data_minority),random_state=42)

data_balanced=pd.concat([data_minority,data_majority_downsampled])
data_balanced

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,0.071446,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,0.248760
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,0.675780,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,0.830927
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,1.267125,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,-0.973790
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,1.239611,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,-1.672391
11,529-56-3974,B,Mandalay,Member,Male,Electronic accessories,25.51,4,5.1020,-0.878185,3/9/2019,17:03,Cash,102.04,4.761905,5.1020,-0.100540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393,308-47-4913,A,Yangon,Member,Female,Sports and travel,52.26,10,26.1300,0.918624,3/9/2019,12:45,Credit card,522.60,4.761905,26.1300,-0.449840
142,338-65-2210,C,Naypyitaw,Member,Female,Health and beauty,68.60,10,34.3000,1.616738,2/5/2019,19:57,Cash,686.00,4.761905,34.3000,1.238443
230,289-65-5721,B,Mandalay,Normal,Female,Fashion accessories,81.37,2,8.1370,-0.618849,1/26/2019,19:28,Cash,162.74,4.761905,8.1370,-0.275190
551,582-52-8065,B,Mandalay,Normal,Female,Fashion accessories,54.31,9,24.4395,0.774174,2/22/2019,10:49,Cash,488.79,4.761905,24.4395,1.122010
711,728-88-7867,C,Naypyitaw,Member,Female,Home and lifestyle,75.53,4,15.1060,-0.023359,3/19/2019,15:52,Ewallet,302.12,4.761905,15.1060,0.772710

En el contexto del conjunto de datos "bank marketing", la imputaci√≥n puede ser necesaria debido a la presencia de valores faltantes en las caracter√≠sticas o atributos de los registros. Estos valores faltantes pueden surgir por diversas razones, como errores en la recopilaci√≥n de datos, informaci√≥n incompleta o simplemente porque algunos registros no proporcionan ciertos detalles.

La imputaci√≥n se utiliza para llenar estos valores faltantes de manera que el conjunto de datos sea m√°s completo y adecuado para su an√°lisis.